version: "3.9"

services:
  api:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A celery_app.celery worker -l info
    env_file: .env
    depends_on:
      - redis

  beat:
    build: .
    command: celery -A celery_app.celery beat -l info
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
